### ISSUE TITLE
Add support for Razer Huntsman V2 (not Analog)

### ISSUE THREAD

**Issue by marcel151** [1kc/razer-macos#482] opened 2021-11-07 14:06 UTC
Hi, 

I got a new Razer Huntsman V2 with Purple Switches. Unfortunately, Razer-macos does not recognize it. Adding support for it would be great!

**Comment by WrathofthePast** [comment] 2021-11-09 19:11
I can add support, but Openrazer hasn't acquired a pcap yet, so they don't know the transaction id. I inquired about it & they said we can try assuming that it's the same as the Huntsman V2 Analog. Are you up to testing it? If it's not the same, we can brute force guess it. Lmk if you want to do that or wait till Openrazer gets a pcap.

**Comment by marcel151** [comment] 2021-11-09 19:22
Sure. If you tell me what I have to to do I will test it.

**Comment by WrathofthePast** [comment] 2021-11-09 19:45
Your job is really simple: download it using this [link](https://github.com/WrathofthePast/razer-macos/releases/tag/v0.4.6.test) & tell me if it works... that's right, I did it that fast.

**Comment by marcel151** [comment] 2021-11-09 20:08
Yes, that worked. Thank you very much! 
<img width="331" alt="Bildschirmfoto 2021-11-09 um 21 06 32" src="https://user-images.githubusercontent.com/65665570/140996903-f0b8ef3d-7b36-439c-8bb9-58a625a14d65.png">

I can see you added the Huntsman V2 with ID "0x026c", was that just a guess? Since the V2 Analog got "0x0266".

**Comment by WrathofthePast** [comment] 2021-11-09 20:35
> I can see you added the Huntsman V2 with ID "0x026c", was that just a guess? Since the V2 Analog got "0x0266".

No, it wasn't... that's the Product ID (PID) which openrazer already found. The transaction id was needed for ~/librazermacos/src/lib/razerkbd_driver.c. My guess was `0x1F` since that's the Huntsman V2 Analog transaction id. 

>Yes, that worked. Thank you very much!

You're welcome. Can you confirm that you can change the light effects, brightness, etc? It'd appear even if I got the transaction id wrong as 3/4 files would still be correct (razerdevice.c, razerkbd_driver.h, & huntsman_v2.json).

**Comment by marcel151** [comment] 2021-11-09 21:32
> No, it wasn't... that's the Product ID (PID) which openrazer already found. The transaction id was needed for ~/librazermacos/src/lib/razerkbd_driver.c. My guess was `0x1F` since that's the Huntsman V2 Analog transaction id.
Thanks for the explanation.

> You're welcome. Can you confirm that you can change the light effects, brightness, etc? It'd appear even if I got the transaction id wrong as 3/4 files would still be correct (razerdevice.c, razerkbd_driver.h, & huntsman_v2.json).
Yes, that works. I can set the brightness only to 0 or 100%, but I think that's normal?

**Comment by WrathofthePast** [comment] 2021-11-10 14:52
>Yes, that works. I can set the brightness only to 0 or 100%, but I think that's normal?

I don't think so, but can you go in-between 0 & 100% via `FN + F11 & F12`? Note: you have to have "Use F1, F2, etc. keys as standard function keys on external keyboard" enabled in /Systems\ Preferences/Keyboard/Keyboard.

If you can't, then the issue isn't on the razer-macos side or at least isn't the only issue.

**Comment by dhobi** [comment] 2021-11-10 16:02
In addition: You should be able to change the brightness of your keyboard when you open the specific device settings window. You do this by clicking on the device name itself.
In this window you should have a range slider which changes the brightness of your keyboard while moving the range slider handle.

**Comment by WrathofthePast** [comment] 2021-11-10 19:30
@marcel151, here's an [updated version](https://github.com/WrathofthePast/razer-macos/releases/tag/0.4.6.test2). The prior version had 9 instead of 6 rows for the ripple and wheel effects and used the image url for the Huntsman V2 Analog. Both are fixed in this new version.

@dhobi, do you think the former could have caused issue?

**Comment by dhobi** [comment] 2021-11-10 19:52
@WrathofthePast if you are talking about the rows: most probably not, no. Razer hardware is pretty forgivable about sending wrong values. At least this was the case for me so far 😄 

With your change the wheel effect should be correctly centered now. With 9 rows the center point was between row 4/5 so far while it should be on row 3 now (6)

**Comment by marcel151** [comment] 2021-11-11 12:36
> > Yes, that works. I can set the brightness only to 0 or 100%, but I think that's normal?
> 
> I don't think so, but can you go in-between 0 & 100% via `FN + F11 & F12`? Note: you have to have "Use F1, F2, etc. keys as standard function keys on external keyboard" enabled in /Systems\ Preferences/Keyboard/Keyboard.
> 
> If you can't, then the issue isn't on the razer-macos side or at least isn't the only issue.

Yes, I knew that and it's working this way. Just wanted to mention that it only shows 0 and 100% there.

> In addition: You should be able to change the brightness of your keyboard when you open the specific device settings window. You do this by clicking on the device name itself.
> In this window you should have a range slider which changes the brightness of your keyboard while moving the range slider handle.

Ah thank you, that's working. Nevertheless, I mostly set the brightness with fn+F11 or F12.

**Comment by WrathofthePast** [comment] 2021-12-13 21:50
@marcel151, can this issue be closed? v0.4.6 added official support.

**Comment by marcel151** [comment] 2021-12-13 21:52
Sorry, yes it can be closed now.

**Closed** 2021-12-13 21:52 UTC
