### ISSUE TITLE
Software doesn't recognize Huntsman V2 TKL (works for DeathAdder V2)

### ISSUE THREAD

**Issue by hulejman** [1kc/razer-macos#561] opened 2022-02-02 16:29 UTC
Hello, basiclly, software doesnt recognize Huntsman V2 TKL. It it not listend in devices and whereever I click to change RGB effects, it doesnt work for it. It does work for Deathadder V2 tho.

**Comment by jameskip** [comment] 2022-02-03 17:31
Same here. In MacOS.

**Comment by WrathofthePast** [comment] 2022-02-18 16:33
Duplicate of #459

**Closed** 2022-03-13 14:54 UTC
Labels: duplicate
