### ISSUE TITLE
Customisations

### ISSUE THREAD

**Issue by jasonfurry** [1kc/razer-macos#382] opened 2021-05-14 15:18 UTC
Really great project, I enjoy it a lot. Although I would like to request customisable side buttons for mouses (Deathadder v2 in particular), which would complete this amazing setup of drivers. By customisations, I talk about key remapping (like 4th and 5th buttons having the possibility to act like shift and control keys respectively). Thank you for your time.

**Comment by WrathofthePast** [comment] 2021-05-15 13:40
Duplicate of #216

**Comment by jasonfurry** [comment] 2021-05-15 20:10
> Duplicate of #216

Thank you so much for answering! I did follow the guide you listed in #228 and unfortunately, I wasn't able to make razer synapse 2.0 identify my deathadder v2. I was having the same problem as most of the original post users (https://developer.apple.com/forums/thread/649829 **), where after typing the second command in the terminal: sudo kextload /Library/Extensions/RazerHid.kext I wasn't able to allow this extension and repeatedly got "Extension with identifiers com.razer.common.razerhid not approved to load. Please approve using System Preferences." error. I tried to find the answer to my problem throughout the whole discussion and nothing worked (I did go to my security and privacy settings and tried approving everything (obviously including "RzUpdater" and "Rz device engine") in "Accessibility", "input monitoring" and "full disc access" cause one of the comments suggested that. I tried adding "Razer synapse" to all of those privacy folders and still nothing. 

Finally, one person suggested trying executing "sudo kmutil load -z -p /Library/Extensions/RazerHid.kext" command in the terminal, which requires reboot. After the reboot, the initial command " sudo kextload /Library/Extensions/RazerHid.kext" was finally executed, although the terminal renamed the command like this: "Executing: /usr/bin/kmutil load -p /Library/Extensions/RazerHid.kext". No errors or anything after this. I tried restarting my mac several times, tried to juggle the privacy setting of "Rz Updater", "Rz device engine" and "Razer synapse" several times with restarts but still, nothing helped (also I un-plugged and re-plugged my mouse every time I opened razer synapse). 

All in all, I wanted to ask you, maybe you have some ideas how can this be fixed? And the last question is: In your guide on #228 you mentioned "Added the Device Engine Kernel to the kernel consent list (no need to disable SIP)". Could you explain how this can be done? Maybe I missed this important step entirely?

Let me know what you think about this.

**Comment by WrathofthePast** [comment] 2021-05-16 04:23
I apologize that you went through all of those steps as Razer Synapse 2 is not for the Deathadder v2. That guide is meant for devices that used Razer Synapse 2. I should have made that more clear in the guide. Thankfully, the solution for Razer Synapse 3 mice such as the Deathadder v2 is much easier. 

I have a Deathadder v2 & can confirm the following works:
Using any Windows computer (Boot Camp works too), install Synapse 3, set up the buttons w/ the shortcuts for MacOS & store it as an on-board profile. You can remap all buttons and setup Hypershift. It'll now work as intended with MacOS (see note).

Note: When the profile is in use, Razer MacOS does not control the lights or DPI of the mouse (it will see the device though). However, toggling the profile to "Last Used" (white light), will allow the lights & DPI to be control by Razer MacOS. This will disable the buttons, but does allow you to toggle back. There is a total of 5 on-board profiles, so any of that stuff can still be toggled between. The main drawback is that it won't be synced in terms of Color Spectrum to other Razer devices.

**Comment by jasonfurry** [comment] 2021-05-16 08:59
> I apologize that you went through all of those steps as Razer Synapse 2 is not for the Deathadder v2. That guide is meant for devices that used Razer Synapse 2. I should have made that more clear in the guide. Thankfully, the solution for Razer Synapse 3 mice such as the Deathadder v2 is much easier.
> 
> I have a Deathadder v2 & can confirm the following works:
> Using any Windows computer (Boot Camp works too), install Synapse 3, set up the buttons w/ the shortcuts for MacOS & store it as an on-board profile. You can remap all buttons and setup Hypershift. It'll now work as intended with MacOS (see note).
> 
> Note: When the profile is in use, Razer MacOS does not control the lights or DPI of the mouse (it will see the device though). However, toggling the profile to "Last Used" (white light), will allow the lights & DPI to be control by Razer MacOS. This will disable the buttons, but does allow you to toggle back. There is a total of 5 on-board profiles, so any of that stuff can still be toggled between. The main drawback is that it won't be synced in terms of Color Spectrum to other Razer devices.

Well I'm quite impressed that I haven't tried that before haha. I think what made me believe that it will work is this sentence from your guide: "The beautiful part is that despite the Razer Core X Chroma never using Synapse 2, it is able to keep it synced with the mouse" and that kept me going till the end. I will try your method later on today, but i wanted to ask about the current stage of razer synapse 2.0 and my mac status. All that fancy coding I did in terminal, will it have any effect on my mac or macOS? Maybe i can revert everything back to the original state before all the recovery mode and default mode terminal command writing?

Talking about the colours and DPI I don't really need changing of the patterns, since I use only the same DPI and colour wave effect is by farm my favourite mode, so maybe I don't even need razer macOS. 

Anyway, thank you so much for such a great tip you gave me about those customisations! This is exactly what i wanted :)

**Closed** 2021-05-25 07:48 UTC
