### ISSUE TITLE
Deathadder Elite: RGB settings don't stick when switching to a Windows PC and back

### ISSUE THREAD

**Issue by markbiswas** [1kc/razer-macos#234] opened 2021-02-08 18:09 UTC
This issue started in Big Sur. On my Deathadder Elite, I've disabled RGB on both Windows and Mac. If I:

1. Switch the Deathadder from Windows to Mac.
2. Switch back to macOS

RGB will be re-enabled. I have to disable it again in Razer macOS, but it'll come back by itself if I repeat the above steps.

**Comment by dhobi** [comment] 2021-03-13 10:25
I see this as possible duplicate of #207. Let's track the progress there.

**Closed by dhobi** 2021-03-13 10:25 UTC
