### ISSUE TITLE
Razer macOS is damaged and can't be opened. You should move it to the bin

### ISSUE THREAD

**Issue by CHarrisMedia** [1kc/razer-macos#449] opened 2021-09-06 22:47 UTC
Hi I get the following error on M1 Macbook pro, Big Sur 11.5.2 (20G95)

Razer macOS is damaged and can't be opened. You should move it to the bin

I have tried removing/reinstalling, no success. I also do not get the option to "Open" from within Security > General.

The non-arm download works without issue.

**Comment by overcurrent** [comment] 2021-09-06 23:18
Hi,

I tried to replicate this and am getting the same error with this package: https://github.com/1kc/razer-macos/releases/download/v0.4.5/Razer.macOS-0.4.5-arm64.dmg

Could you try the one I built in my fork with my M1 Air, this works fine on my computer at least: https://github.com/overcurrent/razer-macos/releases/download/v0.4.6-arm64/Razer.macOS-0.4.5-arm64.dmg.zip

**Comment by fcoury** [comment] 2021-09-07 00:24
@overcurrent thanks for that. I just installed a fresh M1 Mac and I am getting the same error with both the official release and your zip.

**Comment by overcurrent** [comment] 2021-09-07 05:23
@fcoury and @CHarrisMedia thank you for the feedback. It looks like a quarantine extended attribute is set by for example OS X web browser (e.g. Safari) you use to download the app for applications that are not properly signed and/or from unidentified developer. You can confirm this by running: 
xattr Razer\ macOS.app

and it should return: com.apple.quarantine

However, in the meanwhile I could make the official arm64 build also run on my computer by issuing the following command in Terminal in /Applications folder after moving the .app there:

xattr -r -d com.apple.quarantine Razer\ macOS.app

That removes the quarantine attribute and should get rid of the warning. At least it did for me.

Let me know if this helps tackle the warning.

The issue is described for example here: https://derflounder.wordpress.com/2012/11/20/clearing-the-quarantine-extended-attribute-from-downloaded-applications/

I need to investigate how to fix this (proper code signing worst case or some other workaround if it exists).

**Comment by overcurrent** [comment] 2021-09-07 20:12
@fcoury and @CHarrisMedia Could you please try this test version here: 
https://github.com/overcurrent/razer-macos/releases/download/v0.4.6-arm64/Razer-macOS.app-arm64-0.4.6-test.zip

I used ad-hoc signing on both the .app and .zip file on my M1 Air and now when you download the app, unpack it and move it to /Applications you should hopefully experience following steps and get it working without fiddling in the Terminal.

1) Right-click 'Razer macOS.app' and click Open. You'll be first presented with following warning by OS X. Click OK:
![image](https://user-images.githubusercontent.com/67387064/132404210-fe02b0ea-4e49-49f1-9cdc-901c0b580cdc.png)

2) Right-click again on the app and click Open. This time the dialog has changed to following and you can click Open:
![image](https://user-images.githubusercontent.com/67387064/132404335-68147d16-bc11-4ffd-aa32-09ea533432c9.png)

After that the app should open without any nag screens.

My understanding so far is that to really make the arm64 build streamlined for the user (i.e. without any nag screens) one has to use paid Developer ID to code sign the builds.

However, if the above works it's better than before.

**Comment by overcurrent** [comment] 2021-09-08 04:57
Hi @fcoury and thanks for additional testing. I assume that the same warning dialog persisted even if you clicked "OK" and tried to open the app again with a right-click + Open from the menu.

However, could you try if following helps after trying to open the app for the first time:

_Go to Security & Privacy. Click the Open Anyway button in the General pane to confirm your intent to open or install the app._

(The image below is from my computer after downloading the zip, unpacking it, moving the .app to /Applications and trying to open it once with a right-click and Open.)

![image](https://user-images.githubusercontent.com/67387064/132447663-b23f6120-9d0f-49ff-aa6d-6f78c5012da8.png)

The warning prompt should reappear allowing you to Open the app.

**Comment by overcurrent** [comment] 2021-09-08 16:27
@1kc Hi, would you be able to help me test couple of things found during the course of this thread?

1) Build both x86_64 and arm64 targets directly from the master (https://github.com/1kc/razer-macos) using your Intel Mac and send me download link to the arm64 dmg. I'll test whether it's just the 'quarantine extended attribute' that gets set by OS X during download process and whether I can fix the app with xattr. At the same time it gets tested if arm64 package built with Intel machine works.

- This gives us two possibilities to fix/mitigate the issue if the theory holds:
-- Apple Silicon users can fix the unsigned app extracted from the dmg with xattr with given instructions
-- Proper signing with Developer ID should prevent OS X stamping apps with quarantine attribute

2) Codesign both the arm64 'Razer macOS.app' and the zip archive containing it:

- 2a) codesign --force --deep -s - Razer\ macOS.app
- 2b) add Razer\ macOS.app to an archive e.g. 'Razer macOS.app.zip'
- 2c) codesign --force --deep -s - Razer\ macOS.app.zip

- Share the download link to the zip archive and I'll test it too.

- This gives us two possibilities to fix/mitigate the issue if I run the package successfully eventually:
-- Apple Silicon users can launch the app from unidentified developer after allowing it to run from Security & Privacy Settings
-- Proper signing with Developer ID should allow running the app without any nag screens

**Comment by 1kc** [comment] 2021-09-09 00:33
@overcurrent Here is the entire dist directory built off master branch on my Intel Mac
https://a.tmp.ninja/MLyQEGVH.zip

**Comment by overcurrent** [comment] 2021-09-09 04:21
> @1kc Hi, would you be able to help me test couple of things found during the course of this thread?
> 
> 1. Build both x86_64 and arm64 targets directly from the master (https://github.com/1kc/razer-macos) using your Intel Mac and send me download link to the arm64 dmg. I'll test whether it's just the 'quarantine extended attribute' that gets set by OS X during download process and whether I can fix the app with xattr. At the same time it gets tested if arm64 package built with Intel machine works.
> 
> * This gives us two possibilities to fix/mitigate the issue if the theory holds:
>   -- Apple Silicon users can fix the unsigned app extracted from the dmg with xattr with given instructions
>   -- Proper signing with Developer ID should prevent OS X stamping apps with quarantine attribute
> 
> 1. Codesign both the arm64 'Razer macOS.app' and the zip archive containing it:
> 
> * 2a) codesign --force --deep -s - Razer\ macOS.app
> * 2b) add Razer\ macOS.app to an archive e.g. 'Razer macOS.app.zip'
> * 2c) codesign --force --deep -s - Razer\ macOS.app.zip
> * Share the download link to the zip archive and I'll test it too.
> * This gives us two possibilities to fix/mitigate the issue if I run the package successfully eventually:
>   -- Apple Silicon users can launch the app from unidentified developer after allowing it to run from Security & Privacy Settings
>   -- Proper signing with Developer ID should allow running the app without any nag screens

@1kc Thank you. I can say the test was successful in a way.

**Here's my findings for test case no. 1:**
- xattr returns com.apple.qurantine flag for the downloaded zip from tmp.ninja 
- after extracting it and trying to open 'Razer\ macOS.app' I'm getting the error message 'Razer macOS is damaged and can't be opened. You should move it to the bin.' that this thread is also based on
- xattr returns com.apple.qurantine flag for the extracted  'Razer\ macOS.app'
- using 'xattr -r -d com.apple.quarantine Razer\ macOS.app' removes the com.apple.quarantine flag and actually starts the application but then I hit the same Javascript error you faced with the x86_64 package built on my M1 Air (this as another issue already)

**Conclusion for case no.1:** 
- arm64 package built from current master using M1 hardware and using 'xattr -r -d com.apple.quarantine Razer\ macOS.app' for the application itself before launching should result in a healthy application file user can launch
- arm64 package built with an Intel Mac breaks for Javascript error even after using xattr but this is another issue. Same thing happens if x86_64 package built with M1 is tried to launch with Intel Mac. Workaround now is to keep on building arm64 on M1 and x86_64 on Intel.
- I would assume that if the application package is signed with Developer ID certificate quarantine flag would not be set

**Here's my findings for test case no. 2:**
- code signing the 'Razer\ macOS.app' with an ad-hoc signature and then adding it to a zip archive which is also ad-hoc signed with codesign was uploaded to tmp.ninja
- the downloaded zip file has com.apple.quarantine flag set
- the extracted 'Razer\ macOS.app' has com.apple.quarantine flag set
- after trying to launch 'Razer\ macOS.app' without doing anything else results in warning 'Razer macOS” can’t be opened because Apple cannot check it for malicious software.'
- going to Security & Privacy under System Preferences and clicking "Open Anyway" allows opening the application
- Same Javascript error hits after this but the signing issue is solved

**Conclusion for case no.2:** 
- if arm64 package is codesigned and zipped to an archive which is also codesigned user should be able to bypass the warning via Security & Privacy settings
- I would assume that if the application package is signed with Developer ID certificate none of this is an issue

**Comment by 1kc** [comment] 2021-09-09 05:47
@overcurrent Thanks for that detective work. Do you have a Developer ID yourself? The 99 USD a year subscription is a bit off-putting.

**Comment by overcurrent** [comment] 2021-09-09 19:25
@1kc No problem. Yes I actually revived my old subscription but I need to wait for Apple to perform couple of change requests to my account. They have at least two business day turn-around time for anything one asks so we'll need to wait until I can test the proper signing so that Gatekeeper won't go nuts on everyone else's M1 Macs...

**Comment by overcurrent** [comment] 2021-09-10 22:16
@fcoury and @CHarrisMedia I've now code signed the build using Developer ID and Apple notarized the package just recently.

Let me know if this works and if it does we can finally close this issue and @1kc can update the arm64 package on this official repository.

Successful notarization should mean that the package also now runs on your M1 Macs. Please try this:
https://github.com/overcurrent/razer-macos/releases/download/v0.4.6-arm64/Razer.macOS-0.4.5-arm64.dmg

On a first launch you'll likely get a very non-intrusive heads up from OS X as follows:
![image](https://user-images.githubusercontent.com/67387064/132923113-253d9fa9-0002-4c88-af93-3b621935a64d.png)

**Comment by fcoury** [comment] 2021-09-10 23:27
@overcurrent guess what? It works **flawlessly**. Thanks so much for all the hard work!

**Comment by CHarrisMedia** [comment] 2021-09-10 23:54
Works great now for me too. Thanks.

**Comment by overcurrent** [comment] 2021-09-10 23:56
That's great to hear!

@1kc you can close this issue and update the arm64 package from the link I provided for this official repository.

**Comment by 1kc** [comment] 2021-09-11 02:45
Awesome! Done!

**Closed by 1kc** 2021-09-11 02:45 UTC
