### ISSUE TITLE
still not working for blackwidow v3 tkl

### ISSUE THREAD

**Issue by BenJaine** [1kc/razer-macos#259] opened 2021-02-17 23:03 UTC
after reading the patch notes my keyboard still doesnt get detected

**Comment by dhobi** [comment] 2021-02-18 07:52
Duplicate of #249, #88
The keyboard added in v.0.3.6 is BlackWidow V3 (ProductId: 0x024e) while you want support for BlackWidow V3 Tenkeyless (ProductId: 0x0a24).

**Comment by Bryghton42** [comment] 2021-03-03 13:28
> after reading the patch notes my keyboard still doesnt get detected

Try changing the on board profiles and then changing the colors.

**Comment by dhobi** [comment] 2021-03-06 12:27
For state updates on BlackWidow V3 Tenkeyless: #276

**Closed by dhobi** 2021-03-06 12:27 UTC
